version: '3'
services:
  server:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    working_dir: /web
    volumes:
      - .:/web
      - ./site.conf:/etc/nginx/conf.d/site.conf

  app:
    build: .
    container_name: app
    volumes:
      - .:/web
      
  composer:
    restart: 'no'
    image: composer:1.9.3
    command: install
    volumes:
      - .:/app
      
  db:
    image: yobasystems/alpine-mariadb
    container_name: db_server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - db_volume:/var/lib/mysql

volumes:
  db_volume:
